# 单机 1/4/8×RTX 4090：DDP/FSDP Benchmark

这个 Notebook 只保留服务器实验的高层操作：配置、预检、运行和展示。命令构造、断点复用、超时、日志、重复聚合、质量门禁、CSV/JSON/PNG 落盘都由 `distributed_bench_utils.py` 和 `run_dist_bench.py` 完成。

可以顺序执行全部单元。已完成且 identity 匹配的 raw case 会自动复用；只有设置 `rerun_existing=True` 才会强制重跑。

## 0. 会话配置

8 卡服务器保持默认 `(1, 4, 8)`；4 卡服务器改成 `(1, 4)`。Notebook kernel 必须使用安装了当前项目、PyTorch CUDA、pandas 和 matplotlib 的同一个 Python 环境。

In [1]:
import sys
from importlib import import_module
from pathlib import Path

ROOT = next(
    path for path in (Path.cwd().resolve(), *Path.cwd().resolve().parents)
    if (path / 'tests' / 'distributed_bench_utils.py').is_file()
)
sys.path.insert(0, str(ROOT / 'tests'))

bench_utils = import_module('distributed_bench_utils')
BenchmarkSettings = bench_utils.BenchmarkSettings
DistributedBenchmark = bench_utils.DistributedBenchmark

settings = BenchmarkSettings(
    world_sizes=(1, 4),
    strategies=('single', 'ddp', 'fsdp'),
    model_config='configs/model_125m_moe.yaml',
    local_batch=4,
    capacity_batches=(1, 2, 4, 8, 16, 32, 64, 128),
    warmup_steps=10,
    measure_steps=30,
    repeats=3,
)
bench = DistributedBenchmark(
    root=ROOT,
    output='artifacts/distributed_benchmark/rtx4090_125m_moe',
    settings=settings,
)

## 1. 服务器预检与硬件清单

预检会验证当前 kernel 的 Python/CUDA、可见 GPU 数、`torch.distributed`、`nvidia-smi`、模型配置和全部拓扑 YAML。硬件清单另外保存 GPU、驱动、PCIe/NVLink 拓扑、Git commit 与 dirty 状态。

In [2]:
preflight = bench.preflight()
inventory = bench.inventory()
preflight, inventory

RUN /home/ubuntu/mini-train-sys/.venv/bin/python /home/ubuntu/mini-train-sys/scripts/run_dist_bench.py inventory --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/inventory

{
  "timestamp_utc": "2026-07-20T19:28:44.435776+00:00",
  "hostname": "ml-ubuntu22-04-desktop-v3-2-128gb-25m",
  "platform": "Linux-5.15.0-72-generic-x86_64-with-glibc2.35",
  "python": "3.10.12 (main, Jun 22 2026, 18:55:27) [GCC 11.4.0]",
  "cpu_count": 44,
  "torch": "2.5.1+cu118",
  "cuda": "11.8",
  "nvidia_smi": "GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-800e09d3-f879-3678-3a81-d0b5be4877f4)\nGPU 1: NVIDIA GeForce RTX 4090 (UUID: GPU-0caa5d5c-3a92-327e-6a71-f81c81521bca)\nGPU 2: NVIDIA GeForce RTX 4090 (UUID: GPU-c1d23de5-ac10-5852-c4f5-8fa33b1bd368)\nGPU 3: NVIDIA GeForce RTX 4090 (UUID: GPU-2baa5c33-c7d5-2ce5-7953-44529fffab63)",
  "gpu_inventory": "0, NVIDIA GeForce RTX 4090, 24564 MiB, 525.105.17, 00000000:29:00.0\n1, NVIDIA GeForce RTX 4090, 24564 MiB, 525.105.17, 00000000:2C:00.0\n2, NVIDIA GeForce RTX 4090, 24564 MiB, 525.105.17, 00000000:2F:00.0\n3, NVIDIA GeForce RTX 4090, 24564 MiB, 525.105.17, 00000000:32:00.0",
  "topology": "\u001b[4mGPU0\tGPU1\tGPU2\tGPU3\tCPU Affinity\tNUMA Affinity\u001b[0m\nGPU0\t X \tSYS\tSYS\tSYS\t0-10\t0\nGPU1\tSYS\t X \tSYS\tSYS\t11-21\t1\nGPU2\tSYS\tSYS\t X \tSYS\t22-32\t2\nGPU3\tSYS\tSYS\tSYS\t X \t33-43\t3\n\nLegend:\n\n  X    = Self\n  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)\n  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node\n  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)\n  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)\n  PIX  = Connection traversing at most a single PCIe bridge\n  NV#  = Connection traversing a bonded set of # NVLinks",
  "git_commit": "bde795e3daae7b92be2a7a6e48c2e7ccb8d7bcb1",
  "git_status": "M .gitignore\n M docs/benchmarks/distributed_benchmark.md\n M scripts/run_dist_bench.py\n M tests/distributed_bench_utils.py\n M tests/distributed_server_benchmark.ipynb\n M tests/test_distributed_bench_utils.py\n?? AGENTS.md\n?? HISTORY.md\n?? artifacts"
}

({'ok': True,
  'root': '/home/ubuntu/mini-train-sys',
  'python': '/home/ubuntu/mini-train-sys/.venv/bin/python',
  'torch': '2.5.1+cu118',
  'cuda': '11.8',
  'visible_gpus': 4,
  'requested_world_sizes': (1, 4),
  'strategies': ('single', 'ddp', 'fsdp'),
  'output': '/data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe',
  'errors': [],
  'warnings': []},
 {'timestamp_utc': '2026-07-20T19:28:44.435776+00:00',
  'hostname': 'ml-ubuntu22-04-desktop-v3-2-128gb-25m',
  'platform': 'Linux-5.15.0-72-generic-x86_64-with-glibc2.35',
  'python': '3.10.12 (main, Jun 22 2026, 18:55:27) [GCC 11.4.0]',
  'cpu_count': 44,
  'torch': '2.5.1+cu118',
  'cuda': '11.8',
  'nvidia_smi': 'GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-800e09d3-f879-3678-3a81-d0b5be4877f4)\nGPU 1: NVIDIA GeForce RTX 4090 (UUID: GPU-0caa5d5c-3a92-327e-6a71-f81c81521bca)\nGPU 2: NVIDIA GeForce RTX 4090 (UUID: GPU-c1d23de5-ac10-5852-c4f5-8fa33b1bd368)\nGPU 3: NVIDIA GeForce RTX 4090 (UUID: GPU-2baa5c33-c7d5-2ce5-7953-44529fffab63)',
  'gpu_inventory': '0, NVIDIA GeForce RTX 4090, 24564 MiB, 525.105.17, 00000000:29:00.0\n1, NVIDIA GeForce RTX 4090, 24564 MiB, 525.105.17, 00000000:2C:00.0\n2, NVIDIA GeForce RTX 4090, 24564 MiB, 525.105.17, 00000000:2F:00.0\n3, NVIDIA GeForce RTX 4090, 24564 MiB, 525.105.17, 00000000:32:00.0',
  'topology': '\x1b[4mGPU0\tGPU1\tGPU2\tGPU3\tCPU Affinity\tNUMA Affinity\x1b[0m\nGPU0\t X \tSYS\tSYS\tSYS\t0-10\t0\nGPU1\tSYS\t X \tSYS\tSYS\t11-21\t1\nGPU2\tSYS\tSYS\t X \tSYS\t22-32\t2\nGPU3\tSYS\tSYS\tSYS\t X \t33-43\t3\n\nLegend:\n\n  X    = Self\n  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)\n  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node\n  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)\n  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)\n  PIX  = Connection traversing at most a single PCIe bridge\n  NV#  = Connection traversing a bonded set of # NVLinks',
  'git_commit': 'bde795e3daae7b92be2a7a6e48c2e7ccb8d7bcb1',
  'git_status': 'M .gitignore\n M docs/benchmarks/distributed_benchmark.md\n M scripts/run_dist_bench.py\n M tests/distributed_bench_utils.py\n M tests/distributed_server_benchmark.ipynb\n M tests/test_distributed_bench_utils.py\n?? AGENTS.md\n?? HISTORY.md\n?? artifacts'})

## 2. Weak scaling

固定每卡 local batch，比较 1→4→8 卡的吞吐、P50/P95 step 延迟、扩展效率、数据等待和显存。默认同时运行 DDP 与 FSDP。每个 case 独立 `torchrun`，10 次 warmup、30 次测量、3 次重复。

In [3]:
weak = bench.run_weak()
weak.show()

RUN /home/ubuntu/mini-train-sys/.venv/bin/python /home/ubuntu/mini-train-sys/scripts/run_dist_bench.py run --suite weak --strategies single ddp fsdp --world-sizes 1 4 --model-config configs/model_125m_moe.yaml --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak --case-timeout-seconds 1800 --local-batch 4 --warmup-steps 10 --measure-steps 30 --repeats 3

{
  "timestamp_utc": "2026-07-20T19:28:47.150311+00:00",
  "hostname": "ml-ubuntu22-04-desktop-v3-2-128gb-25m",
  "platform": "Linux-5.15.0-72-generic-x86_64-with-glibc2.35",
  "python": "3.10.12 (main, Jun 22 2026, 18:55:27) [GCC 11.4.0]",
  "cpu_count": 44,
  "torch": "2.5.1+cu118",
  "cuda": "11.8",
  "nvidia_smi": "GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-800e09d3-f879-3678-3a81-d0b5be4877f4)\nGPU 1: NVIDIA GeForce RTX 4090 (UUID: GPU-0caa5d5c-3a92-327e-6a71-f81c81521bca)\nGPU 2: NVIDIA GeForce RTX 4090 (UUID: GPU-c1d23de5-ac10-5852-c4f5-8fa33b1bd368)\nGPU 3: NVIDIA GeForce RTX 4090 (UUID: GPU-2baa5c33-c7d5-2ce5-7953-44529fffab63)",
  "gpu_inventory": "0, NVIDIA GeForce RTX 4090, 24564 MiB, 525.105.17, 00000000:29:00.0\n1, NVIDIA GeForce RTX 4090, 24564 MiB, 525.105.17, 00000000:2C:00.0\n2, NVIDIA GeForce RTX 4090, 24564 MiB, 525.105.17, 00000000:2F:00.0\n3, NVIDIA GeForce RTX 4090, 24564 MiB, 525.105.17, 00000000:32:00.0",
  "topology": "\u001b[4mGPU0\tGPU1\tGPU2\tGPU3\tCPU Affinity\tNUMA Affinity\u001b[0m\nGPU0\t X \tSYS\tSYS\tSYS\t0-10\t0\nGPU1\tSYS\t X \tSYS\tSYS\t11-21\t1\nGPU2\tSYS\tSYS\t X \tSYS\t22-32\t2\nGPU3\tSYS\tSYS\tSYS\t X \t33-43\t3\n\nLegend:\n\n  X    = Self\n  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)\n  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node\n  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)\n  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)\n  PIX  = Connection traversing at most a single PCIe bridge\n  NV#  = Connection traversing a bonded set of # NVLinks",
  "git_commit": "bde795e3daae7b92be2a7a6e48c2e7ccb8d7bcb1",
  "git_status": "M .gitignore\n M docs/benchmarks/distributed_benchmark.md\n M scripts/run_dist_bench.py\n M tests/distributed_bench_utils.py\n M tests/distributed_server_benchmark.ipynb\n M tests/test_distributed_bench_utils.py\n?? AGENTS.md\n?? HISTORY.md\n?? artifacts"
}
RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/single_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 4 --warmup-steps 10 --measure-steps 30 --repeat 0 --case-identity f56ca7e77c1238c79e1a31e5012a89e1b73460328be25bc2d338bf2de050f804 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/raw/weak_single_1gpu_b4_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/single_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 4 --warmup-steps 10 --measure-steps 30 --repeat 1 --case-identity 6032b8d05b8efb3cbf11b6bf3ecea1e76b9e4a078fcdae99e61f3110dcbf2299 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/raw/weak_single_1gpu_b4_r1.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/single_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 4 --warmup-steps 10 --measure-steps 30 --repeat 2 --case-identity 732924e69ef52abf3b4f8b54fadffabc235331af39ba659eef6bb9857456bf3b --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/raw/weak_single_1gpu_b4_r2.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 4 --warmup-steps 10 --measure-steps 30 --repeat 0 --case-identity 56b618b4a96275b2b1cc290661c99088fa92b0e50dd29484b8cc9f0f7431f4f7 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/raw/weak_ddp_1gpu_b4_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 4 --warmup-steps 10 --measure-steps 30 --repeat 1 --case-identity b3781e6fc42b90f686327b768c71908547f633a05d9978d8ed69660e74c7fc99 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/raw/weak_ddp_1gpu_b4_r1.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 4 --warmup-steps 10 --measure-steps 30 --repeat 2 --case-identity d7c63cbbebcafcab2f811489bc7d60a5c7c018ee9ccb0433101427f322ae5f2e --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/raw/weak_ddp_1gpu_b4_r2.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 4 --warmup-steps 10 --measure-steps 30 --repeat 0 --case-identity 6d350580661ff3eb58b4e4693c1c18ed1a5d416dfd667264cf6a2589f9ed1606 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/raw/weak_ddp_4gpu_b4_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 4 --warmup-steps 10 --measure-steps 30 --repeat 1 --case-identity 529c977632aa3615ddf17ce8b54e7a9ea0fd1a11393b12a20c1a8e1983a0c0e4 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/raw/weak_ddp_4gpu_b4_r1.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 4 --warmup-steps 10 --measure-steps 30 --repeat 2 --case-identity cfc40bc344552abeeb961ce87e1a256ac84d03f0c9dfaca98d284f76e275dda7 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/raw/weak_ddp_4gpu_b4_r2.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 4 --warmup-steps 10 --measure-steps 30 --repeat 0 --case-identity ce9ad9c3d5faa5b0b602613980bc66694f253c36083df4a5ac8cdacc9fa79eb5 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/raw/weak_fsdp_1gpu_b4_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 4 --warmup-steps 10 --measure-steps 30 --repeat 1 --case-identity 23f1359bc6453a5aad42921b0eb16d65df7dbe2f897cb1b358e3410efc951f43 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/raw/weak_fsdp_1gpu_b4_r1.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 4 --warmup-steps 10 --measure-steps 30 --repeat 2 --case-identity f0611eda44ba24a5f7e9911a073119f5db703f7900d723134273a15efd4e03e8 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/raw/weak_fsdp_1gpu_b4_r2.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 4 --warmup-steps 10 --measure-steps 30 --repeat 0 --case-identity a683b5ca5329b242e93c783880f681befb916c1b5cc058312b9a9d3c4164d7fa --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/raw/weak_fsdp_4gpu_b4_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 4 --warmup-steps 10 --measure-steps 30 --repeat 1 --case-identity 172559d389a1e5cc624fc37f5e7ae1e5e817a4a934ade14b6b65d698227818ef --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/raw/weak_fsdp_4gpu_b4_r1.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 4 --warmup-steps 10 --measure-steps 30 --repeat 2 --case-identity 8d0a793b28a974e8a62957226c472128a79f5f275ece5a0cb946dbe1004f4c6f --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/raw/weak_fsdp_4gpu_b4_r2.json

completed=15 failed=0

Results

,strategy,world_size,local_batch_size,global_batch_size,repeats_successful,step_time_ms_p50,step_time_ms_p95,throughput_tokens_per_sec,weak_scaling_efficiency_percent,peak_memory_allocated_mb,system_peak_memory_allocated_mb,memory_utilization_percent,data_stall_percent,workers_per_node
0,ddp,1,4,4,3,106.308,108.751,38432.744,100.000,10269.436,10269.436,42.405,0.143,4.0
1,ddp,4,4,16,3,266.188,277.737,61180.094,39.797,10269.436,41077.742,42.405,0.138,16.0
2,fsdp,1,4,4,3,112.395,115.793,36440.293,100.000,8408.990,8408.990,34.723,0.136,4.0
3,fsdp,4,4,16,3,253.219,260.309,64451.095,44.217,3672.635,14674.806,15.165,0.121,16.0
4,single,1,4,4,3,102.166,103.496,40103.004,100.000,8294.447,8294.447,34.250,0.164,4.0

Quality gates

{'runs_succeeded': 15,
 'runs_failed': 0,
 'all_requested_repeats_completed': True,
 'weak_scaling_efficiency_ge_80pct': False,
 'data_stall_le_5pct': True,
 'memory_headroom_ge_10pct': True}

Saved artifacts

{'results': '/data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/presentation/results_aggregated.csv',
 'failures': '/data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/presentation/failures.csv',
 'metrics': '/data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/presentation/quality_gates.json',
 'figure': '/data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/presentation/weak_overview.png',
 'readme': '/data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/presentation/README.md'}

{'results': PosixPath('/data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/presentation/results_aggregated.csv'),
 'failures': PosixPath('/data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/presentation/failures.csv'),
 'metrics': PosixPath('/data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/presentation/quality_gates.json'),
 'figure': PosixPath('/data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/presentation/weak_overview.png'),
 'readme': PosixPath('/data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/weak/presentation/README.md')}

## 3. Capacity sweep

逐个扫描 local batch。每个 case 位于独立子进程，OOM、超时和其他失败会写入 failure 表而不会污染后续 case；图表给出各策略/卡数的最大成功 local batch 和成功 case 的显存曲线。

In [4]:
capacity = bench.run_capacity()
capacity.show()

RUN /home/ubuntu/mini-train-sys/.venv/bin/python /home/ubuntu/mini-train-sys/scripts/run_dist_bench.py run --suite capacity --strategies single ddp fsdp --world-sizes 1 4 --model-config configs/model_125m_moe.yaml --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity --case-timeout-seconds 1800 --batch-sizes 1 2 4 8 16 32 64 128 --warmup-steps 3 --measure-steps 5 --repeats 1

{
  "timestamp_utc": "2026-07-20T19:34:45.295043+00:00",
  "hostname": "ml-ubuntu22-04-desktop-v3-2-128gb-25m",
  "platform": "Linux-5.15.0-72-generic-x86_64-with-glibc2.35",
  "python": "3.10.12 (main, Jun 22 2026, 18:55:27) [GCC 11.4.0]",
  "cpu_count": 44,
  "torch": "2.5.1+cu118",
  "cuda": "11.8",
  "nvidia_smi": "GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-800e09d3-f879-3678-3a81-d0b5be4877f4)\nGPU 1: NVIDIA GeForce RTX 4090 (UUID: GPU-0caa5d5c-3a92-327e-6a71-f81c81521bca)\nGPU 2: NVIDIA GeForce RTX 4090 (UUID: GPU-c1d23de5-ac10-5852-c4f5-8fa33b1bd368)\nGPU 3: NVIDIA GeForce RTX 4090 (UUID: GPU-2baa5c33-c7d5-2ce5-7953-44529fffab63)",
  "gpu_inventory": "0, NVIDIA GeForce RTX 4090, 24564 MiB, 525.105.17, 00000000:29:00.0\n1, NVIDIA GeForce RTX 4090, 24564 MiB, 525.105.17, 00000000:2C:00.0\n2, NVIDIA GeForce RTX 4090, 24564 MiB, 525.105.17, 00000000:2F:00.0\n3, NVIDIA GeForce RTX 4090, 24564 MiB, 525.105.17, 00000000:32:00.0",
  "topology": "\u001b[4mGPU0\tGPU1\tGPU2\tGPU3\tCPU Affinity\tNUMA Affinity\u001b[0m\nGPU0\t X \tSYS\tSYS\tSYS\t0-10\t0\nGPU1\tSYS\t X \tSYS\tSYS\t11-21\t1\nGPU2\tSYS\tSYS\t X \tSYS\t22-32\t2\nGPU3\tSYS\tSYS\tSYS\t X \t33-43\t3\n\nLegend:\n\n  X    = Self\n  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)\n  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node\n  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)\n  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)\n  PIX  = Connection traversing at most a single PCIe bridge\n  NV#  = Connection traversing a bonded set of # NVLinks",
  "git_commit": "bde795e3daae7b92be2a7a6e48c2e7ccb8d7bcb1",
  "git_status": "M .gitignore\n M docs/benchmarks/distributed_benchmark.md\n M scripts/run_dist_bench.py\n M tests/distributed_bench_utils.py\n M tests/distributed_server_benchmark.ipynb\n M tests/test_distributed_bench_utils.py\n?? AGENTS.md\n?? HISTORY.md\n?? artifacts"
}
RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/single_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 1 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity f2d29a6964bf4290a0fc1cccbe189c0746f29b5e848a296f5432018161b274cd --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_single_1gpu_b1_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/single_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 2 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 16129dfe1424b9a9c1f481812ee3b151c8f0af170b004e4849d4b76a3a624daf --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_single_1gpu_b2_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/single_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 4 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 44dcc4767c43cd5ba6e8b98fbc4fffeedbecd8441a41012a092d909af473191f --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_single_1gpu_b4_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/single_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 8 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 46ac1b58cfcf7188a938965fc61a01f87ed240b8587147bd4ff1ebf7b9ea08cd --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_single_1gpu_b8_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/single_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 16 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 6e1b492265879881bc56938177a74f63dabed1123719f9b8a9a164ad99b01844 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_single_1gpu_b16_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/single_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 32 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 0bfbfe6508925192cdee99dbd57df8985437c0eb0651a0667e083c505956bb21 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_single_1gpu_b32_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/single_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 64 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity c7caf39f707ae951b15d980760a80f4a079d98ace480fa13fbe8bc8d4e7c0736 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_single_1gpu_b64_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/single_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 128 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 88e7ad559dab1bfef4a45c7a3f3ba50d4c88c35e7d7eaeaf9a202ac82b660593 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_single_1gpu_b128_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 1 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 149fcd3dbc2c306c9ba994659f481b250e874bed123e088b3afc3ac08ad234b6 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_ddp_1gpu_b1_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 2 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 9309c366161c09f13d8668dedb7d6f8fcbb002121eb852d619d2aad60b8242fa --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_ddp_1gpu_b2_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 4 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 265c51eafa1b25e0e04df6b9e3b21a5d031a4dcf0172d21b7dc6b3536bb19da7 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_ddp_1gpu_b4_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 8 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 92a23d384b9875af862c1da697642b597bb374d4ce37bc7f1c34053b623a315e --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_ddp_1gpu_b8_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 16 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity d45ca329c6dfeb86dc220494f9657ccf1ee9da27323a73ff499ac834539eeec6 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_ddp_1gpu_b16_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 32 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity eef2c290399328520a8afbe34c942258a1cf86c5365ece2c9a30133299e7f6c0 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_ddp_1gpu_b32_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 64 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity e55bc0ae1371da1b5d86dc814242c289d7a30c61104d9ed665bcaf4dfe3d7c14 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_ddp_1gpu_b64_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 128 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 5e1be2724ff21147ce15c76421029e663fde388b0ae7a59ac6c09891d5e07b5b --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_ddp_1gpu_b128_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 1 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 8eb38435ea97618ec2c0a4bbeafe477089737cd467d1e2567bb9831428655691 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_ddp_4gpu_b1_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 2 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 665b4f7ffc06b9506a27df1064c5a4010253e739f91668e14ea595be443ab0d2 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_ddp_4gpu_b2_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 4 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 17a3e1a1a258f1f7ceafb034ce25cd571f00a6fc56ea671b48e39b58759460fe --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_ddp_4gpu_b4_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 8 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity a2d12ec546bb4cbd83484fea9c7e3db4089e9b43c60e3b8b528f8848976952c2 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_ddp_4gpu_b8_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 16 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity d37a7d5c1053f4e6ded98c69317b6edbf87bd1865589829fae1b9e2b24959038 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_ddp_4gpu_b16_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 32 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 30e06e21de623d4204443442c5b4d124316d13d97769c6b9e44759a29db3bae5 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_ddp_4gpu_b32_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 64 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 9399c83e2b600857059a0842368d5d926c39c24177b6fc274cb365dedc64e387 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_ddp_4gpu_b64_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/ddp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 128 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity f69fd795449e5351bfed0582ce59892c7122236e21042bcfab2290b3e26b6430 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_ddp_4gpu_b128_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 1 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity d0d216c7c04fc027651b82e430c6d16bac98bfea7a7e1a860b91a77c18fd473e --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_fsdp_1gpu_b1_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 2 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 82275f7705f9ef2a5c2397534c0c78afb0349434d65ca018ebf9e182570786dd --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_fsdp_1gpu_b2_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 4 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity fe42f4a053bda6b7a06c0d3ef65865fa804c243d6f106dc9c053f14f18a45b63 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_fsdp_1gpu_b4_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 8 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity ccda057ee72d2841364b9e3060edef231e765d08bd243a6a95fa99039627a4c8 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_fsdp_1gpu_b8_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 16 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity fc1f0472e6812945e82eb8bd10bf4da8d31c22e72a78cb0199765bb50855e40d --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_fsdp_1gpu_b16_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 32 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity ba4677b908624b9d665e8b559dadfe3e1f03a6c4818ebf9f4ce32e93775019c1 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_fsdp_1gpu_b32_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 64 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity df204cc2562e557b6031d1a0ef6c200599c2e5b1c848128bf60da499a3cf31da --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_fsdp_1gpu_b64_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 1 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_1gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 128 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 6664fe2459ef000b81fd5be7aab0d6f10d0a3c619346310ea301db6cbb2183a3 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_fsdp_1gpu_b128_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 1 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity cc665dc5c903baa1fca1f8df2afacd8075ae82a8d6928b0ead35199e6fe31664 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_fsdp_4gpu_b1_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 2 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 411fd32f2a5ed004ac4b46bbf24f2c8b0aaee940952205686b438f3d3b9b10fe --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_fsdp_4gpu_b2_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 4 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 41dbde234c6e96afd67defdb6dbc0f602d382bb40e548c5315fc647435ec8236 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_fsdp_4gpu_b4_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 8 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 498d8bdb9ce97773eb872002c3e477d27a7528706e66de5b256235c3adb13c92 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_fsdp_4gpu_b8_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 16 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 422b9e705f36c64598cd6709b9cce35bb76d8f9f7431e8816232787d946dd08d --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_fsdp_4gpu_b16_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 32 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity c4800f1169142cbb91cbf97610a0426ffa96165a2350ee65af65281bba949fe3 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_fsdp_4gpu_b32_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 64 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 04c8f4d85b761fcd27adde3485b5ccd99e8fc4ba653b339cbf78d1a18440b7db --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_fsdp_4gpu_b64_r0.json

RUN /home/ubuntu/mini-train-sys/.venv/bin/python -m torch.distributed.run --standalone --nproc_per_node 4 scripts/run_dist_bench.py _worker --config configs/server/rtx4090_24gb/runs/fsdp_4gpu.yaml --model-config /home/ubuntu/mini-train-sys/configs/model_125m_moe.yaml --batch-size 128 --warmup-steps 3 --measure-steps 5 --repeat 0 --case-identity 14489183030753f0d2156f208e5d0c670fbd5ad0bc7e9b5b803028d5da988304 --output /data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/raw/capacity_fsdp_4gpu_b128_r0.json

completed=30 failed=10

Results

,strategy,world_size,local_batch_size,global_batch_size,repeats_successful,step_time_ms_p50,step_time_ms_p95,throughput_tokens_per_sec,peak_memory_allocated_mb,system_peak_memory_allocated_mb,memory_utilization_percent,data_stall_percent,workers_per_node
0,ddp,1,1,1,1,89.339,90.013,11471.670,8855.721,8855.721,36.568,0.197,4.0
1,ddp,1,2,2,1,89.971,90.180,23081.530,9356.414,9356.414,38.635,0.191,4.0
2,ddp,1,4,4,1,107.053,107.985,38247.610,10269.436,10269.436,42.405,0.114,4.0
3,ddp,1,8,8,1,157.896,158.294,51854.260,11941.217,11941.217,49.309,0.082,4.0
4,ddp,1,16,16,1,264.525,266.445,61818.186,15376.309,15376.309,63.493,0.047,4.0
5,ddp,1,32,32,1,489.461,490.094,66960.998,22436.668,22436.668,92.647,0.032,4.0
6,ddp,4,1,4,1,254.308,255.209,16101.533,8855.721,35422.885,36.568,0.093,16.0
7,ddp,4,2,8,1,259.626,263.149,31482.072,9356.414,37425.656,38.635,0.059,16.0
8,ddp,4,4,16,1,263.335,267.427,61987.724,10269.436,41077.742,42.405,0.101,16.0
9,ddp,4,8,32,1,294.781,295.171,111414.312,11941.217,47764.867,49.309,0.085,16.0
10,ddp,4,16,64,1,357.848,359.287,182923.874,15376.309,61505.234,63.493,0.092,16.0
11,ddp,4,32,128,1,527.789,529.403,248199.801,22436.668,89746.672,92.647,0.061,16.0
12,fsdp,1,1,1,1,112.480,113.063,9205.738,8238.155,8238.155,34.018,0.112,4.0
13,fsdp,1,2,2,1,107.317,109.033,19020.385,8235.920,8235.920,34.008,0.116,4.0
14,fsdp,1,4,4,1,110.051,113.277,37027.030,8408.990,8408.990,34.723,0.116,4.0
15,fsdp,1,8,8,1,142.502,144.252,57387.054,9998.349,9998.349,41.286,0.102,4.0
16,fsdp,1,16,16,1,227.742,229.131,71835.075,13524.841,13524.841,55.848,0.073,4.0
17,fsdp,1,32,32,1,590.512,610.459,58032.649,20587.325,20587.325,85.011,0.024,4.0
18,fsdp,4,1,4,1,248.875,249.681,16458.631,2450.740,9783.273,10.120,0.091,16.0
19,fsdp,4,2,8,1,247.605,248.879,33043.503,2801.996,11179.385,11.570,0.096,16.0
20,fsdp,4,4,16,1,251.290,251.413,65252.821,3672.635,14674.806,15.165,0.090,16.0
21,fsdp,4,8,32,1,276.244,283.449,117805.946,5435.953,21729.782,22.447,0.117,16.0
22,fsdp,4,16,64,1,324.007,324.884,202263.207,8965.567,35845.014,37.021,0.152,16.0
23,fsdp,4,32,128,1,469.760,471.953,278760.373,16028.016,64079.141,66.184,0.059,16.0
24,single,1,1,1,1,84.977,85.181,12278.492,8123.863,8123.863,33.546,0.246,4.0
25,single,1,2,2,1,85.820,86.353,23891.356,8156.509,8156.509,33.680,0.242,4.0
26,single,1,4,4,1,102.967,104.200,39892.101,8294.447,8294.447,34.250,0.136,4.0
27,single,1,8,8,1,153.902,154.711,53244.817,9932.268,9932.268,41.013,0.110,4.0
28,single,1,16,16,1,259.850,261.260,62975.771,13447.010,13447.010,55.526,0.049,4.0
29,single,1,32,32,1,482.321,484.318,67889.357,20504.745,20504.745,84.670,0.029,4.0

Capacity frontier

,strategy,world_size,largest_successful_local_batch,largest_successful_global_batch
0,ddp,1,32,32
1,ddp,4,32,128
2,fsdp,1,32,32
3,fsdp,4,32,128
4,single,1,32,32

Failures / OOM boundary

,strategy,world_size,batch_size,repeat,oom,timed_out,returncode,log,error_tail
0,single,1,64,0,True,False,1,/data/mini-train-sys/artifacts/distributed_ben...,lastic/multiprocessing/api.py:869] failed (exi...
1,single,1,128,0,True,False,1,/data/mini-train-sys/artifacts/distributed_ben...,lastic/multiprocessing/api.py:869] failed (exi...
2,ddp,1,64,0,True,False,1,/data/mini-train-sys/artifacts/distributed_ben...,lastic/multiprocessing/api.py:869] failed (exi...
3,ddp,1,128,0,True,False,1,/data/mini-train-sys/artifacts/distributed_ben...,lastic/multiprocessing/api.py:869] failed (exi...
4,ddp,4,64,0,True,False,1,/data/mini-train-sys/artifacts/distributed_ben...,lastic/multiprocessing/api.py:869] failed (exi...
5,ddp,4,128,0,True,False,1,/data/mini-train-sys/artifacts/distributed_ben...,lastic/multiprocessing/api.py:869] failed (exi...
6,fsdp,1,64,0,True,False,1,/data/mini-train-sys/artifacts/distributed_ben...,lastic/multiprocessing/api.py:869] failed (exi...
7,fsdp,1,128,0,True,False,1,/data/mini-train-sys/artifacts/distributed_ben...,lastic/multiprocessing/api.py:869] failed (exi...
8,fsdp,4,64,0,True,False,1,/data/mini-train-sys/artifacts/distributed_ben...,lastic/multiprocessing/api.py:869] failed (exi...
9,fsdp,4,128,0,True,False,1,/data/mini-train-sys/artifacts/distributed_ben...,"main\n return _run_code(code, main_globals,..."

Saved artifacts

{'results': '/data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/presentation/results_aggregated.csv',
 'failures': '/data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/presentation/failures.csv',
 'metrics': '/data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/presentation/capacity_frontier.json',
 'figure': '/data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/presentation/capacity_overview.png',
 'readme': '/data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/presentation/README.md'}

{'results': PosixPath('/data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/presentation/results_aggregated.csv'),
 'failures': PosixPath('/data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/presentation/failures.csv'),
 'metrics': PosixPath('/data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/presentation/capacity_frontier.json'),
 'figure': PosixPath('/data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/presentation/capacity_overview.png'),
 'readme': PosixPath('/data/mini-train-sys/artifacts/distributed_benchmark/rtx4090_125m_moe/capacity/presentation/README.md')}

## 4. 只重新打开已有结果

重启 Notebook 后不需要重跑实验。使用下面两行重新加载 summary、表格和图片。若确实要无条件重跑 raw case，调用 `bench.run_weak(rerun_existing=True)` 或 `bench.run_capacity(rerun_existing=True)`。

In [5]:
# bench.load('weak').show()
# bench.load('capacity').show()